### PR TITLE
Cleanup commands, fix scrolling

### PR DESCRIPTION
**Pull request by ekulxam**
If possible, please merge #27 before this pull request because this PR deals with commands more extensively
Apologies for not doing this in multiple commits

Changes

- Cleanup command code (permissions, ordering, etc.)
- Fix Shard Tablet screen scrolling too much sometimes
- Removed all usages of the `var` keyword (This might be a bit overkill, though. I understand why someone would want to use the `var` keyword, but I just found it confusing. (For some reason, there was one instance where `var` was being used instead of `int`.) Feel free to replace (or tell me to replace) the longer types (i.e. `Map.Entry<Identifier, JsonElement>` and `CommandNode<FabricClientCommandSource>`).)
- Implemented the view command

For future discussion
- Group together arguments with their (sub)commands
- Change the permission level of all `library` subcommands to 4 to match with `library deleteall` or downgrade `deleteall`'s permission level to 3 for consistency (if I can delete one at a time, why not delete all of them at once?). Additionally, command blocks should never be able to execute library commands (even if they somehow get a permission level of 3 or 4), so there should be a player validation check.

### CODE REVIEW

**Comment by ekulxam** [comment]
If possible, please merge #27 before this pull request because this PR deals with commands more extensively
Apologies for not doing this in multiple commits

Changes

- Cleanup command code (permissions, ordering, etc.)
- Fix Shard Tablet screen scrolling too much sometimes
- Removed all usages of the `var` keyword (This might be a bit overkill, though. I understand why someone would want to use the `var` keyword, but I just found it confusing. (For some reason, there was one instance where `var` was being used instead of `int`.) Feel free to replace (or tell me to replace) the longer types (i.e. `Map.Entry<Identifier, JsonElement>` and `CommandNode<FabricClientCommandSource>`).)
- Implemented the view command

For future discussion
- Group together arguments with their (sub)commands
- Change the permission level of all `library` subcommands to 4 to match with `library deleteall` or downgrade `deleteall`'s permission level to 3 for consistency (if I can delete one at a time, why not delete all of them at once?). Additionally, command blocks should never be able to execute library commands (even if they somehow get a permission level of 3 or 4), so there should be a player validation check.

**Comment by sisby-folk** [comment]
@ekulxam set for a merge. no objections to the var removals here.

**Comment by ekulxam** [comment]
Sorry, I haven't been able to work on this very much. I'll see what I can do to solve #30 and fix the conflicts in time for Modfest 1.21 opening day.

**Comment by ekulxam** [comment]
Reopening because I accidentally nuked the PR
I'll look into fixing #30 now

**Review by falkreon — APPROVED** [review]
It's good to get these vars out of the codebase, even though I'm responsible for a few of them X)

The only place I'd ever consider keeping them is something like CommandNode&lt;ServerCommandSource&gt;, but even then, here it wouldn't help clarity. So to me, this looks ready to go.

**Pull request merged**
